services:
  - type: web
    name: potato-disease-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install --upgrade pip && pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
